### PR TITLE
Add tags object and servers object 

### PR DESCRIPTION
**Pull request by Ifedolapo-9**
I grouped the endpoints and added a base url

### CODE REVIEW

**Comment by Ifedolapo-9** [comment]
Screenshot (358)

Hello nomike, the picture attached shows how the docs look on Swagger Editor after I made the changes.

**Comment by Ifedolapo-9** [comment]
The next thing I want to do if you will accept is to begin to write descriptions of each endpoint. 

For example, for the Get Label Types Endpoints: I would say, "Get label types for an assortment box".

What do you think?

**Comment by nomike** [comment]
Hi @Ifedolapo-9,

I have to reject your pull request as Samuel already contributed a very similar change.
I will however, grab a few things from your change (e.g. the base URL) and incorporate it in the code.

But regardless of that, thanks a lot for your contribution.
It's the first time I actually have contributors for one of my projects outside of a work-context and it's really great to have help.

cheers

nomike

**Comment by Ifedolapo-9** [comment]
Oh,
Alright.
It's nice working with you too.
Thanks.

**Pull request closed without merging**
